name: "conftest kubernetes action"
description: "Write structured tests and validate your configuration files using Open Policy Agent"
author: "joaoss35"
inputs:
  combine:
    description: "Combine all config files to be evaluated together"
    default: true
    required: false
  token:
    description: "The token to make pull requests comments possible"
    default: ""
    required: false
  namespace:
    description: "The namespace where the policies will be tested"
    default: "main"
    required: false
  output:
    description: "The output format for Conftest results"
    default: "stdout"
    required: false
  parser:
    description: "The parser that will be used to parse the configurations"
    default: "yaml"
    required: false
  file:
    description: "The path for the files that will be tested"
    default: "."
    required: true
  policy:
    description: "The path where the Rego policy can be found"
    default: "policy"
    required: false
  comment:
    description: "A pull-request comment with the test output"
    default: ""
    required: false
  trace:
    description: "Enable more verbose trace output for Rego queries"
    default: false
    required: false
  update:
    description: "A list of policies that will be downloaded before the tests run"
    default: ""
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    COMBINE: ${{ inputs.combine}}
    TOKEN: ${{ inputs.token}}
    NAMESPACE: ${{ inputs.namespace}}
    OUTPUT: ${{ inputs.output}}
    PARSER: ${{ inputs.parser}}
    FILE: ${{ inputs.file}}
    POLICY: ${{ inputs.policy}}
    COMMENT: ${{ inputs.comment}}
    TRACE: ${{ inputs.trace}}
    UPDATE: ${{ inputs.update}}

branding:
  color: orange
  icon: lock
